"""Create Game Model

Revision ID: 45e8d3b337df
Revises: e45e08a4f6b2
Create Date: 2024-09-18 03:47:19.396763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e8d3b337df'
down_revision = 'e45e08a4f6b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
